In [42]:
import pandas as pd
import numpy as np

In [43]:
credits = pd.read_csv("credits.csv")
movies = pd.read_csv("movies.csv")

In [44]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   movie_id  4803 non-null   int64 
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 93.9+ KB


In [45]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [46]:
merged = pd.concat([movies,credits[['movie_id','cast','crew']]], axis =1)

In [47]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [48]:
merged = merged[['movie_id','title', 'overview','genres', 'keywords', 'cast', 'crew']]

In [49]:
merged.dropna(inplace = True)

In [50]:
merged.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [51]:
import ast

In [52]:
def convert_genre(z):
    L = []
    for i in ast.literal_eval(z):
        L.append(i["name"])
    return L


In [53]:
merged['genres'] = merged['genres'].apply(convert_genre)

In [54]:
merged['keywords'] = merged['keywords'].apply(convert_genre)

In [55]:
merged.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [56]:
def convert_cast(x):
    L = []
    counter = 0
    for i in ast.literal_eval(x):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
        return L

In [57]:
merged['cast'] = merged['cast'].apply(convert_cast)

In [58]:
merged['cast']

0       [Sam Worthington]
1           [Johnny Depp]
2          [Daniel Craig]
3        [Christian Bale]
4         [Taylor Kitsch]
              ...        
4798    [Carlos Gallardo]
4799       [Edward Burns]
4800        [Eric Mabius]
4801      [Daniel Henney]
4802     [Drew Barrymore]
Name: cast, Length: 4800, dtype: object

In [59]:
def convert_director(x):
    L = []
    for i in ast.literal_eval(x):
        if i['job']=='Director':
            L.append(i['name'])
            return L
        

In [60]:
merged['crew'] = merged["crew"].apply(convert_director)

In [61]:
merged.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords               cast  \
0  [culture clash, future, space war, space colon...  [Sam Worthington]   
1  [ocean, drug abuse, exotic island, east india ...      [Johnny Depp]   
2  [spy, based on novel, secret agent, sequel, mi...     [Daniel Craig]   
3  [dc comics, crime fighter, terrorist, secret i...   [Christian Bale]   
4  [based on novel, mars, medallion, space travel...    [Taylor Kitsch]   

                  crew  
0      [James Cameron]  
1     [Gore Verbinski]  
2         [Sam Mendes]  
3  [Christopher Nolan]  
4     [Andrew Stanton]

In [62]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4800 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   movie_id  4800 non-null   int64 
 1   title     4800 non-null   object
 2   overview  4800 non-null   object
 3   genres    4800 non-null   object
 4   keywords  4800 non-null   object
 5   cast      4758 non-null   object
 6   crew      4770 non-null   object
dtypes: int64(1), object(6)
memory usage: 187.5+ KB


In [63]:
merged.dropna(inplace = True)

In [64]:
merged.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords               cast  \
0  [culture clash, future, space war, space colon...  [Sam Worthington]   
1  [ocean, drug abuse, exotic island, east india ...      [Johnny Depp]   
2  [spy, based on novel, secret agent, sequel, mi...     [Daniel Craig]   
3  [dc comics, crime fighter, terrorist, secret i...   [Christian Bale]   
4  [based on novel, mars, medallion, space travel...    [Taylor Kitsch]   

                  crew  
0      [James Cameron]  
1     [Gore Verbinski]  
2         [Sam Mendes]  
3  [Christopher Nolan]  
4     [Andrew Stanton]

In [65]:
merged['genres'] = merged['genres'].apply(lambda x: [i.replace(" ", '') if i else '' for i in x])
merged['keywords'] = merged['keywords'].apply(lambda x: [i.replace(" ", '') if i else '' for i in x])
merged['crew'] = merged['crew'].apply(lambda x: [i.replace(" ", '') if i else '' for i in x])
merged['cast'] = merged['cast'].apply(lambda x: [i.replace(" ", '') if i else '' for i in x])


In [66]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4749 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   movie_id  4749 non-null   int64 
 1   title     4749 non-null   object
 2   overview  4749 non-null   object
 3   genres    4749 non-null   object
 4   keywords  4749 non-null   object
 5   cast      4749 non-null   object
 6   crew      4749 non-null   object
dtypes: int64(1), object(6)
memory usage: 185.5+ KB


In [67]:
merged['overview'] = merged['overview'].apply(lambda x : x.split())

In [68]:
merged['crew']

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...        
4798     [RobertRodriguez]
4799         [EdwardBurns]
4800          [ScottSmith]
4801          [DanielHsia]
4802     [BrianHerzlinger]
Name: crew, Length: 4749, dtype: object

In [69]:
merged['tags'] = merged['overview']+merged['genres']+merged['keywords']+merged['cast']+merged['crew']

In [70]:
merged['tags']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...                        
4798    [El, Mariachi, just, wants, to, play, his, gui...
4799    [A, newlywed, couple's, honeymoon, is, upended...
4800    ["Signed,, Sealed,, Delivered", introduces, a,...
4801    [When, ambitious, New, York, attorney, Sam, is...
4802    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4749, dtype: object

In [71]:
new = merged[['movie_id', 'title', 'tags']]

In [72]:
new['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'JamesCameron']

In [73]:
new['tags'] = new['tags'].apply(lambda x: ' '.join(x))

<ipython-input-73-2bb4c4f2a77a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(lambda x: ' '.join(x))


In [74]:
new['tags'] = new['tags'].apply(lambda x:x.lower())

<ipython-input-74-8a2dbbadbcc3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(lambda x:x.lower())


In [75]:
new.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

In [91]:
import nltk

In [92]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [97]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [76]:
new.to_csv('final-content-filtering.csv', index = False)

In [100]:
new['tags'] = new['tags'].apply(stem)

<ipython-input-100-0d6b095c9b14>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(stem)


In [77]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words="english")

In [78]:
cv.fit_transform(new['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [101]:
vectors = cv.fit_transform(new['tags']).toarray()

In [102]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [103]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [104]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [95]:
ps.stem("running")

'run'

In [98]:
stem(new['tags'][0])

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington jamescameron'

In [110]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vectors)

array([[1.        , 0.08718573, 0.08718573, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08718573, 1.        , 0.0625    , ..., 0.02451452, 0.        ,
        0.02695819],
       [0.08718573, 0.0625    , 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02451452, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02695819, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [111]:
cosine_similarity(vectors).shape

(4749, 4749)

In [112]:
similarity = cosine_similarity(vectors)

In [113]:
similarity[1]

array([0.08718573, 1.        , 0.0625    , ..., 0.02451452, 0.        ,
       0.02695819])

In [123]:
sorted(similarity[0], reverse=True)[1:10]

[0.2828678574017678,
 0.26401000024165,
 0.26155718717359333,
 0.26130213378560535,
 0.25112360116696136,
 0.24784079854830487,
 0.24784079854830487,
 0.2460905535784756,
 0.24534987303147354]

In [128]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1]) [1:10]

[(1213, 0.2828678574017678),
 (3720, 0.26401000024165),
 (539, 0.26155718717359333),
 (507, 0.26130213378560535),
 (61, 0.25112360116696136),
 (1201, 0.24784079854830487),
 (2403, 0.24784079854830487),
 (582, 0.2460905535784756),
 (1191, 0.24534987303147354)]

In [132]:
def recommend(movie):
    movie_index = new[new['title'] == movie].index[0]
    distances = similarity[movie_index]
    moviesList = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1]) [1:10]
    
    for i in moviesList:
        print(new.iloc[i[0]].title)

In [134]:
new[new['title'] == 'Avatar'].index[0]

0

In [133]:
recommend('Avatar')

Aliens vs Predator: Requiem
Falcon Rising
Titan A.E.
Independence Day
Jupiter Ascending
Predators
Aliens
Battle: Los Angeles
Small Soldiers


In [131]:
new.iloc[1216]

movie_id                                                11172
title                                        Music and Lyrics
tags        a wash up singer is given a coupl day to compo...
Name: 1216, dtype: object